### ISSUE TITLE
Cryptol-as-a-library writes to stdout

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#443] opened 2017-09-14 23:41 UTC
When loading a module, Cryptol will write a message to the console indicating what module it is loading.  When using Cryptol as a library, this can clobber wire protocols that are being communicated on stdout.

We should remove used of `putStr` and `putStrLn`, and replace them with a more disciplined mechanism for output.

**Comment by atomb** [comment] 2017-09-26 23:14
Duplicate of #166.

**Closed** 2017-09-26 23:16 UTC
