### ISSUE TITLE
Cryptol Crash when using == on two polymorphic functions

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#243] opened 2015-06-19 18:33 UTC
Given the following Cryptol source file:
```
a x = x + x
b x = x * 2
```
The following command crashes Cryptol:
```
Main> a == b
Assuming a = 2
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  398708dd41e6ac3c25fbd9497ccf2067d3f6fd8f
  Branch:    master (non-committed files present during build)
  Location:  [Eval] lexCompare
  Message:   invalid type
%< --------------------------------------------------- 
```
However, if I force a monomorphic type on the functions...
```
a x = x + (x:[8])
b x = x * (2:[8])
```
I get no crash and the following type error, which is expected since we're using `==` instead of `===`.
```
Main> a == b

[error] at <interactive>:1:1--1:7:
  Unsolved constraint:
    Cmp ([8] -> [8])
      arising from
      use of expression (==)
      at <interactive>:1:1--1:7
```

**Comment by elliottt** [comment] 2015-06-19 19:00
When I have that commit checked out, and I use the same input program, I'm unable to reproduce your error:

```
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.3.0 (398708d)

Loading module Cryptol
Cryptol> :l test.cry
Loading module Cryptol
Loading module Main
Main> :t a
a : {a} (Arith a) => a -> a
Main> :t b
b : {a} (Arith a) => a -> a
Main> :t a == b

[error] at <interactive>:1:1--1:7:
  The inferred type for (expression) is ambiguous.
Main> a == b

[error] at <interactive>:1:1--1:7:
  The inferred type for (expression) is ambiguous.
Main>
```

Have you tried a completely fresh build?

**Comment by jpziegler** [comment] 2015-06-19 19:17
Did a `make squeaky`, `git pull` to the latest, and still get the crash:
```
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.3.0 (63c62b3)

Loading module Cryptol
Cryptol> :l triple_equal.cry 
Loading module Cryptol
Loading module Main
Main> :t a
a : {a} (Arith a) => a -> a
Main> :t b
b : {a} (fin a, a >= 2) => [a] -> [a]
Main> :t a == b
a == b : {a} (Cmp ([a] -> [a]), fin a, a >= 2) => Bool
Main> a == b
Assuming a = 2
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  63c62b3cf865544f0e6ed8418dfc051c5e307c6e
  Branch:    master (non-committed files present during build)
  Location:  [Eval] lexCompare
  Message:   invalid type
%< --------------------------------------------------- 
```
I'm noticing that the type of your function `b` doesn't match the type of mine. Did you define it the same way I did?

**Comment by elliottt** [comment] 2015-06-19 20:09
I hadn't defined the same function; I had:

```
b x = x * x
```

With that change, the crash appears for me, so I'll take a look :)

**Comment by elliottt** [comment] 2015-06-19 20:24
The resulting term expects to find a `Cmp` instance for `[a] -> [a]`, and somehow finds one :)

```
Main> :set debug=on
Main> a == b
Assuming a = 2
(\{a} (Cmp ([a] -> [a]), fin a, a >= 2) ->
 Cryptol::== ([a] -> [a]) <> (Main::a [a] <>) (Main::b a <> <>)) 2 <> <> <>
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< ---------------------------------------------------
  Revision:  398708dd41e6ac3c25fbd9497ccf2067d3f6fd8f
  Branch:    HEAD (non-committed files present during build)
  Location:  [Eval] lexCompare
  Message:   invalid type
%< ---------------------------------------------------
```

I think that we should probably just rule out cases like this in the class constraint solver.  Currently, we can only say "yes with these additional constraints" or "can't say for sure" from this part of the solver, but there are a number of cases where we should just fail right away.

**Comment by yav** [comment] 2015-06-19 21:04
Yeah, there are two problems here, I'll have a go at fixing them:
  * The bug is that one we default for the REPL we only look at the numeric constraints, and ignore the rest!
  * Also, it would be nice to implement what Trevor suggests, where we report and error, when we know that something is certainly not solvable, like that `Cmp (a -> b)` constraint.

**Comment by yav** [comment] 2015-06-19 23:14
OK, both of these should be fixed on `master`.

**Closed by yav** 2015-06-19 23:14 UTC
