### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#199] opened 2015-04-14 18:37 UTC
In addition to #141, I would like to be able to use unicode characters. For example, XOR could be referred to by '^' as well as '⊕' (U+2295) and '⨁' (U+2A01).

**Comment by elliottt** [comment] 2015-06-03 18:48
This is fixed by ae6b5dc3e88c4ccf99e371e3c3715921a6a7cbad, as you can now define a synonym for `^` like this:

```
(⊕) : {a} Arith a => a -> a -> a
x ⊕ y = x ^ y
```

**Comment by dylanmc** [comment] 2015-06-03 19:41
Before you go nuts, please note that Unicode support on Windows is uneven. If you want your Cryptol programs to be robustly portable, use restraint.

**Comment by auricratio** [comment] 2015-06-04 13:41
Oh Sean and I are models of restraint.

**Comment by weaversa** [comment] 2015-06-04 14:05
As proof, I haven't even *attempted* to merge these changes.

**Comment by weaversa** [comment] 2015-06-04 16:07
Muhhahahhaha!
```
(**) : {a} Arith a => a -> a -> a
x ** y = x ^^ y
```

**Comment by elliottt** [comment] 2015-06-04 17:26
The power! :)

**Comment by weaversa** [comment] 2020-01-18 19:40
```
(⊕) : {a} Arith a => a -> a -> a
x ⊕ y = x ^ y
```

```
Main> :t (⊕)
() : ()
Main> 10 ⊕ 11
[warning] at <interactive>:1:6--1:8:
  Defaulting type argument 'rep' of 'number' to [4]

[error] at <interactive>:1:1--1:8:
  Type '?rep`902 -> ?<expr>::(expression)`899' does not support literals.
```

**Comment by weaversa** [comment] 2020-01-18 19:40
Unicode doesn't seem to work anymore.

**Comment by yav** [comment] 2020-01-21 23:52
Which version of Cryptol is this with?  I tried it with the current `master` (3038eacf5423113e) and it seems to work (on Linux):
```
Main> :t (⊕)
(⊕) : {a} (Arith a, Logic a) => a -> a -> a
```

**Comment by weaversa** [comment] 2020-01-22 00:08
I'm running it on OSX. Maybe that's the problem?

```
(⊞) : {a} (fin a) => [a*8] -> [a*8] -> [a*8]
x ⊞ y = join (groupBy`{8} x + groupBy`{8} y)

(%%) : {a} (fin a) => [a*8] -> [a*8] -> [a*8]
x %% y = join (groupBy`{8} x + groupBy`{8} y)

(⊕) : {a} (Arith a, Logic a) => a -> a -> a
x ⊕ y = x ^ y
```

```
version 2.8.1 (1e883e9, modified)
https://cryptol.net  :? for help

Loading module Cryptol
Cryptol> :l test.cry
Loading module Cryptol
Loading module Main
Main> :t (⊕)
() : ()
Main> :t (%%)
(%%) : {a} (fin a) => [8 * a] -> [8 * a] -> [8 * a]
```

**Comment by brianhuffman** [comment] 2020-01-22 02:03
I'm on OSX, and it works fine for me:
```
version 2.8.1 (ce0365f, modified)
https://cryptol.net  :? for help

Loading module Cryptol
Loading module Main
Main> :l Unicode2.cry
Loading module Cryptol
Loading module Main
Main> :t (⊕)
(⊕) : {a} (Arith a, Logic a) => a -> a -> a
Main> :t (%%)
(%%) : {a} (fin a) => [8 * a] -> [8 * a] -> [8 * a]
```
But I haven't upgraded to 10.15 Catalina yet; I wonder if there is some breakage of the `readline` library on the latest MacOS?

**Comment by dylanmc** [comment] 2020-01-22 15:18
I just tried the example on my 2.8.0 installation on Catalina:

```
cryptol
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.8.0

Loading module Cryptol
Cryptol> :l unicode.cry 
Loading module Cryptol
Loading module Main
Main> :t (⊕)
(⊕) : {a} (fin a) => [8 * a] -> [8 * a] -> [8 * a]
```
seems to work. Hmmm.

**Comment by atomb** [comment] 2020-01-22 16:47
This is also working for me on Catalina (10.15.2) with both 2.8.0 and the latest commit (3038eac).

**Comment by yav** [comment] 2020-01-22 18:21
It looks like for some reason the unicode character is being ignored and we are reporting the type of unit, which is why it says `() : ()`.   @weaversa could you have a look at what locale you are using (the `locale` command should let a whole lot of variable, usually all set to the same thing).

**Comment by weaversa** [comment] 2020-01-23 00:35
Ok. It happens when I run `cryptol` from within `emacs` using `comint-run`, which is how I often use Cryptol. If I run `cryptol` directly from `bash` I have no problem.

**Closed** 2020-05-04 22:23 UTC

**Comment by brianhuffman** [comment] 2020-05-04 22:25
This might be a problem with the `haskeline` library, or with `emacs`. We haven't reproduced the problem on our end.
