### ISSUE TITLE
Potential precedence problem?

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#253] opened 2015-06-29 01:24 UTC
This smells fishy to me.
```
Cryptol> :s warnDefaulting=off
Cryptol> 2 == 1+1
True
Cryptol> 3 == 1+1+1

[error] at <interactive>:1:1--1:11:
  Unsolvable constraint:
    Arith Bit
      arising from
      use of expression (+)
      at <interactive>:1:1--1:11
[error] at <interactive>:1:10--1:11:
  Type mismatch:
    Expected type: Bit
    Inferred type: [?j15]
  where
  ?j15 is type parameter 'bits'
          of literal or demoted expression
          at <interactive>:1:10--1:11
```
Whereas using parens or swapping the two sides works fine.
```
Cryptol> 3 == (1+1+1)
True
Cryptol> 1+1+1 == 3
True
```

**Comment by elliottt** [comment] 2015-06-29 01:51
This is the same bug as in #247.  The issue is that infix operators are parsed initially as left-associative, then fixed-up using the precedence table during renaming.  The current implementation resolves precedence in a top-down manner, which causes it to commit prematurely to an operator ordering when there could be operators of lower precedence further to the left.  The pass needs to be changed to work bottom-up, so that operators of lower precedence will bubble out, instead of just being ordered locally.

**Comment by elliottt** [comment] 2015-06-29 23:56
This should be fixed now:

```
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.3.0 (4d469fa)

Loading module Cryptol
Cryptol> 3 == 1 + 1 + 1
[warning] at <interactive>:1:1--1:15:
  Defaulting type parameter 'bits'
             of literal or demoted expression
             at <interactive>:1:14--1:15
  to 2
True
```

**Closed by elliottt** 2015-06-29 23:56 UTC
