### ISSUE TITLE
Symbolic execution much much much slower than concrete execution

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#189] opened 2015-03-16 20:16 UTC
This might be an SBV problem, or a Cryptol problem. I'm not sure.

The test in `examples/SHA1.cry` is slow to execute concretely:
```
$ cryptol2
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.1.0 (489a926)

Loading module Cryptol
Cryptol> :s warnDefaulting=off
Cryptol> :l examples/SHA1.cry 
Loading module Cryptol
Loading module Main
Main> :! date
Mon Mar 16 16:08:50 EDT 2015
Main> :check
property testsPass Using exhaustive testing.
  0%
passed 1 tests.
Q.E.D.
Main> :!date
Mon Mar 16 16:11:39 EDT 2015
```
But, when `:prove` is used, instead of `:check`, after 8 minutes `cryptol` has used 4.8 gigs of RAM and has not yet even called the solver.

Does someone see where it is getting stuck? Perhaps this is the next good example for optimization.

**Comment by acfoltzer** [comment] 2015-03-16 21:05
So, that file includes the following test:

```
t3 = sha1 [ 'a' | i <- [1..1000000] ] ==
     0x34AA973CD4C4DAA4F61EEB2BDBAD27316534016F
```

Since there aren't any variables here, this is of limited value for optimizing the symbolic simulator because the real answer probably is to just fall back to the concrete evaluator when there's nothing symbolic.

@LeventErkok, do you think SBV might benefit from this example as a stress test for concrete evaluation?

**Comment by acfoltzer** [comment] 2015-03-16 21:06
Also, this is out of my range of expertise, but if we were able to find a way to summarize a sequence of hashing a million characters that's shorter than actually running the hash function that many times, wouldn't that mean the hash function isn't very good? :wink:

**Comment by LeventErkok** [comment] 2015-03-17 01:01
Does Cryptol use the exact same interpreter for both the ":prove" mode and in the concrete case?

In Cryptol-1, these two modes used different code bases. I don't know if Cryptol-2 unified them or not.

In any case, yes; SBV can use some optimizations; though I'm not sure if it'll ever be able to do the million-'A's SHA case; the overhead is just too much. I do remember this program being problematic even in the days of Cryptol-1.. If someone were to profile and look at some hot-spots, that'd be awesome. (At least we can identify if it's in the evaluator itself, or in pure SBV code.)

**Comment by brianhuffman** [comment] 2015-03-17 03:47
It's not *exactly* the same interpreter, but the proof backend and the concrete interpreter do share a fair amount of code and data structures, and we've been working to get them to share even more. Ideally, `:prove` on concrete input should have the same asymptotic behavior as the concrete interpreter, with a constant slowdown due to the more heavyweight implementations of the basic primitives. If this is not the case, we should do some profiling to see what's going wrong.

...OK, I just did some simple measurements, timing `:sat \x -> x == sha1 ['a' | i <- [1 .. n]]` for various `n`. Here are the results:

    n=1000  t=0.433s
    n=2000  t=1.095s
    n=3000  t=2.922s
    n=4000  t=5.929s
    n=5000  t=9.591s
    n=6000  t=14.629s
    n=7000  t=20.603s
    n=8000  t=29.912s
    n=9000  t=35.577s
    n=10000  t=48.870s

The time is clearly at least quadratic in the length. I'll do some profiling later and see whether the time is taken up by Cryptol code or SBV.

**Comment by LeventErkok** [comment] 2015-03-17 05:41
@brianhuffman What do the times look like for the same experiment when done in the concrete mode?

**Comment by brianhuffman** [comment] 2015-03-17 14:45
Here are similar measurements for concrete evaluation of `sha1 ['a' | i <= [1 .. n]]`:

    n = 1000  t = 0.255s
    n = 2000  t = 0.412s
    n = 3000  t = 0.566s
    n = 4000  t = 0.758s
    n = 5000  t = 0.874s
    n = 6000  t = 1.078s
    n = 7000  t = 1.176s
    n = 8000  t = 1.305s
    n = 9000  t = 1.573s
    n = 10000  t = 1.653s

**Comment by LeventErkok** [comment] 2015-03-17 17:23
So that could still be either the symbolic evaluator or SBV itself; most likely a combination of the two. 

On the SBV side, I'm wondering if some #PACK# pragmas over the SBV type would help here as there's a lot of onion peeling going on as we look inside SBVs Kinds etc over and over.

**Comment by brianhuffman** [comment] 2015-03-17 17:45
I just did a profiling run, and it looks like 70% of the time is spent evaluating the `split` primitive on the huge input list: this is a *single* call to the `unpackWord` function, which transforms a bitvector into a list of bits. Much of the rest of the time is taken up by lots of calls to `packWord`, which does the opposite.

I'll reimplement `split` in terms of the word-level split operations, and see if there are any other bottlenecks remaining afterward.

**Comment by LeventErkok** [comment] 2015-03-17 17:54
unpackWord seems to be precisely SBVs blastBE; which suffers from the same slowdown issues for large words. Not sure if you can do much here, but if you can fix it in SBV and directly use from there, that'd be good. (Perhaps the "reverse" stuff can be removed, at the least; and then an explicit "go" style loop can help a bit?)

**Comment by brianhuffman** [comment] 2015-03-17 23:00
Commit 37cb5880fd66d5c76213e5223682df4d540d182a fixes most of the performance problems, although for larger sizes it looks like there is still a quadratic time component, just with a much smaller constant. I'll keep the ticket open until I figure out what else is going on here. Maybe we could drop two or three "much"s from the issue name.

@LeventErkok: The major slowdown was due to `sbvTestBit`; I got a big speedup by replacing `x .&. bit i /= 0` with `extract i i x == 1`. Instead of a mask and compare all at the huge bit width, I do an extract and compare at a bit size of 1. `fromBitsBE` is similarly sped up by doing `cat` operations on 1 bit words instead of using so many huge words.

It would be nice to port the faster `sbvTestBit` and `fromBitsBE` to SBV, but you would either need to add a `SWord1` type or else wait for me to finish LeventErkok/sbv#124 :)

**Comment by LeventErkok** [comment] 2015-03-18 00:45
@brianhuffman 

Of course the irony here is that it was you who removed 1-bit-words from SBV and replaced it with KBool: https://github.com/LeventErkok/sbv/commit/88ac87c8bc53f8063f16811a4d7cc695c91dff6d

:-)

Yes; I think that performance bottleneck does need to be addressed, but I'm happy to wait till #124 is addressed. I'll open a ticket for SBV so we can track.

**Comment by brianhuffman** [comment] 2015-03-18 03:52
@LeventErkok, you apparently misunderstand what my changeset LeventErkok/sbv@88ac87c8bc53f8063f16811a4d7cc695c91dff6d did: I didn't remove 1-bit words from SBV, in fact I made it possible to use them! Before I introduced `KBool`, SBV made it *impossible* to use the 1-bit word type in SMTLib, because the translation from SBV confused it with SMTLib's boolean type. You'd better go back and read the commit message again :)

**Comment by LeventErkok** [comment] 2015-03-18 04:06
@brianhuffman Huh, that does appear to be the case indeed. I'm getting too old for this stuff.

Perhaps we should've kept both; and made `KUnbounded False 1` to be proper 1-bit words.. Hindsight is 20/20 of course. But with the planned work on SBV.Dynamic, this'll indeed be possible, no?

**Comment by weaversa** [comment] 2015-03-21 13:00
Here is another (undoubtedly more important) instance of excruciatingly slow symbolic simulation.
```
$ cryptol2 docs/ProgrammingCryptol/aes/AES.cry
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.1.0 (1587c01)

Loading module Cryptol
Loading module AES
<snip>
AES> :s smtfile=aes.smt
AES> :s prover=offline
AES> :prove AESCorrect 
Writing to SMT-Lib file aes.smt...
```

**Comment by brianhuffman** [comment] 2015-03-21 16:38
@weaversa: I tried running your new example with profiling enabled for both Cryptol and SBV, and I'm getting some funny profiling output: The actual runtime is more than two minutes, but ghc reports the total time as only 8.62 seconds. I'm going to keep looking into this...

**Comment by LeventErkok** [comment] 2015-03-21 21:10
I've a pure Haskell/SBV implementation of AES, and symbolic simulation takes almost no time:

    https://hackage.haskell.org/package/sbv-4.2/docs/Data-SBV-Examples-Crypto-AES.html

I stick to using 32-bit chunks of data there for input, but that shouldn't really make a ton of difference as AES will chop the input into blocks anyhow even if you start with a full 128-bit input. Weird.

**Comment by weaversa** [comment] 2015-08-17 17:55
Yeah, this is still horribly bad. Any new ideas?

**Comment by brianhuffman** [comment] 2016-03-14 17:07
I re-profiled the `sha1 ['a' | i <- [1 .. n]]` example with `n` up to 64000, and now it runs in totally linear time. I'll consider that part of the ticket closed.

The slowdown with AES seems to have a totally different source. For `:prove AESCorrect` there is still a large discrepancy between the actual runtime (~2.5 min) and the profiler's reported runtime (~7s). Running cryptol with `+RTS -s` shows the reason:

    15,641,240,040 bytes allocated in the heap
     2,842,981,512 bytes copied during GC
       467,809,768 bytes maximum residency (21 sample(s))
         6,626,712 bytes maximum slop
              1076 MB total memory in use (0 MB lost due to fragmentation)

                                       Tot time (elapsed)  Avg pause  Max pause
    Gen  0     30907 colls,     0 par   140.965s  142.428s     0.0046s    0.0191s
    Gen  1        21 colls,     0 par    2.085s   2.436s     0.1160s    0.8370s

    TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

    SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

    INIT    time    0.000s  (  0.000s elapsed)
    MUT     time    7.050s  (  7.410s elapsed)
    GC      time  143.050s  (144.864s elapsed)
    RP      time    0.000s  (  0.000s elapsed)
    PROF    time    0.000s  (  0.000s elapsed)
    EXIT    time    0.007s  (  0.041s elapsed)
    Total   time  150.110s  (152.315s elapsed)

    Alloc rate    2,218,708,762 bytes per MUT second

    Productivity   4.7% of total user, 4.6% of total elapsed

Cryptol is allocating a lot of memory and spending a ridiculously large proportion of its time doing garbage collection (>95%). Profiling indicates that a large portion of the allocation is caused by the `pmult` and `pmod` primitives, so I'll experiment with alternative ways to define these to try and speed things up.

**Comment by brianhuffman** [comment] 2016-03-15 00:50
Further profiling of Cryptol and SBV shows that `String`-based pretty printing functions in SBV are responsible for a large amount of allocation. Using a different datatype for pretty printing might help significantly.

**Comment by acfoltzer** [comment] 2016-06-29 22:41
@brianhuffman, @LeventErkok, are these `String` issues still outstanding?

**Comment by LeventErkok** [comment] 2016-06-29 23:53
@brianhuffman @acfoltzer 

When the output is really long, then I suspect this is an issue; though I'm not sure if it's the bottleneck.

The sad news is that I tried to replace the backend with a more "datatype" based output, which then gets pretty-printed. I didn't try to optimize too much, but my brief experiment suggested that going through an internal data-type is too costly. (i.e., it was slower than String.) Perhaps using Text or some modern variant might pay off, though needs experimentation.

I'd suggest punting on this unless it's hitting you guys on a regular basis.

**Comment by robdockins** [comment] 2016-07-14 00:23
After testing the initial problem report with the new evaluator, this still seems to be a problem.

Given that the symbolic and concrete evaluators are now tightly unified, this suggests an underlying issue with SBV.  For both the concrete and symbolic evaluators, over 50% of the time is spent performing 'joinWord' operations; however the symbolic evaluator seems to generate more long-lived garbage.  This gradually causes GC time to overwhelm productive time, and the symbolic evaluator thus takes much longer to run.

**Comment by LeventErkok** [comment] 2016-07-14 03:22
@robdockins I'm not following.

Are you saying the symbolic simulator is *slow* even when used with concrete-only values?

If that's the case, then that's a separate issue that needs to be investigated. (Note that SBV *should* be constant folding everything that's a constant, and thus not creating an SMTLib file at all.)

The original issue was about translating the final program to SMT-Lib, which is done using Strings. That doesn't seem to match with your description; as you seem to be suggesting it's slow even in the complete concrete case.

(Mind you, I *do* expect it to be slower/more costly in the completely concrete case, but not by a huge factor. The original ticket was about symbolic runs.)

**Comment by robdockins** [comment] 2016-07-14 03:51
@LeventErkok As best I can tell, there's two separate issues going on in this ticket.  The first is the slowness of the SHA1 test vectors under the symbolic simulator, as reported by @weaversa in the initial report. This problem is what I was referring to above.  As you say, I believe it is constant folding the entire computation in this case; but in a way that seems to generates considerably more GC activity than in the concrete simulator.  I don't fully understand why.

For concreteness, the icry interaction I was using to do symbolic computation is:
```
:l examples/SHA1.cry
:sat \x -> x == sha1 [ 'a' | i <- [1..50000] ]
```

And for concrete computation is:
```
:l examples/SHA1.cry
sha1 [ 'a' | i <- [1..50000] ]
```

The second problem identified in this ticket is the slowness of generating simulation and generating the SMT file for the AES correctness property.  This problem seems related to using Strings for pretty-printing, and is better tracked using ticket LeventErkok/SBV#216 instead, I think.

**Comment by LeventErkok** [comment] 2016-07-14 05:07
@acfoltzer Indeed! There are two issues here.

For the "compile thru String:" As I mentioned in https://github.com/LeventErkok/sbv/issues/216#issuecomment-196594819, I think it's best to punt on that till it really is an issue. If you're generating a real large SMTLib so the difference really becomes a problem, then I'd think that it's a real hard problem the SMT solver is unlikely going to succeed on anyways. If you find counter-examples to that, I'd love to hear.

Regarding the "1-million-SHA" problem: Again, surely evaluation through SBV will be expensive: At each operation it'll do a "am I concrete or not" check: That adds up when you're doing one-million A's, which will be much slower. I'm not sure why the space grows too badly however; so an investigation into that would be much appreciated. Perhaps you can spare some cycles on that and submit a patch? Or at least identify some cost centers?

**Comment by robdockins** [comment] 2016-07-15 20:31
The "1-million-SHA" problem appears to largely be a space leak.  LeventErkok/sbv#230 squashes the most obvious space leak.  This brings mutator productivity up to around 87%, which is on par with the concrete evaluator.  The symbolic evaluation is still slower than concrete evaluation, but only by about 25%, which strikes me as acceptable.

I'll open a separate ticket to track the issue with `String` printing, so I think we can close this issue.

**Closed by robdockins** 2016-07-15 20:31 UTC
