### ISSUE TITLE
type checking of selection can fail unexpectedly

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#315] opened 2016-03-08 03:23 UTC
With a recent cryptol,

    x.1 where x = (1,(2,3)).1

is accepted and gives the expected answer, 3.  The similar

    ((1,(2,3)).1).1

is not accepted, giving two unresolved finiteness constraints:

    Cryptol> ((1,(2,3)).1).1
    [warning] at <interactive>:1:1--1:16:
      Defaulting type parameter 'bits'
		 of literal or demoted expression
		 at <interactive>:1:3--1:4
      to 1

    [error] at <interactive>:1:6--1:7:
      Unsolved constraint:
	fin ?t8
	  arising from
	  use of literal or demoted expression
	  at <interactive>:1:6--1:7
      where
      ?t8 is type parameter 'bits'
	     of literal or demoted expression
	     at <interactive>:1:6--1:7
    [error] at <interactive>:1:8--1:9:
      Unsolved constraint:
	fin ?u8
	  arising from
	  use of literal or demoted expression
	  at <interactive>:1:8--1:9
      where
      ?u8 is type parameter 'bits'
	     of literal or demoted expression
	     at <interactive>:1:8--1:9

**Comment by elliottt** [comment] 2016-03-08 04:39
I think this might be the same as #2.

**Comment by yav** [comment] 2016-03-08 04:58
It looks like Cryptol is complaining because it can't figure out how to instantiate the literals.

As far as I can see, these should have been defaulted to the smallest possible size, so we should have a look at why this is not happening.

**Comment by robdockins** [comment] 2016-05-06 20:07
Duplicate of #2

**Closed by robdockins** 2016-05-06 20:07 UTC
