### ISSUE TITLE
TTyApp found when kind checking, but it should have been eliminated already

### ISSUE THREAD

**Issue by ramsdell** [GaloisInc/cryptol#1256] opened 2021-07-27 14:14 UTC
Here is some buggy code that causes an error.  (The curly brackets in the function body should not be there.)

$ cat bug.cry
perm_prop : {n} (fin n) => [n][32] -> Bit
perm_prop p = all (\x -> x < `{n}) p
$ cryptol bug.cry
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.10.0
https://cryptol.net  :? for help

Loading module Cryptol
Loading module Main
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  3cab6e6fd7d8422aad5530215248d49e6e590951
  Branch:    release-2.10.0 (uncommited files present)
  Location:  doCheckType
  Message:   TTyApp found when kind checking, but it should have been eliminated already
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.10.0-inplace:Cryptol.Utils.Panic
  panic, called at src/Cryptol/TypeCheck/Kind.hs:391:24 in cryptol-2.10.0-inplace:Cryptol.TypeCheck.Kind
%< --------------------------------------------------- 

$

**Comment by brianhuffman** [comment] 2021-07-27 14:29
With a recent development version, it looks like this doesn't panic anymore. I'm going to do a bit more testing to see exactly which versions have the bug.

**Comment by brianhuffman** [comment] 2021-07-27 14:42
Duplicate of #962. It was fixed by #1071.

**Closed by brianhuffman** 2021-07-27 14:42 UTC
Labels: bug, duplicate
