### ISSUE TITLE
double copy of "Programming in Cryptol" included in release

### ISSUE THREAD

**Issue by kiniry** [GaloisInc/cryptol#969] opened 2020-11-16 22:59 UTC
The 2.9.1 release includes both `doc/cryptol/Cryptol.pdf` and `doc/cryptol/ProgrammingCryptol.pdf` which are identical.

**Comment by kiniry** [comment] 2020-11-16 23:09
It looks like this started with the 2.9.0 release.  Earlier releases did not have the duplication.

**Comment by brianhuffman** [comment] 2020-11-17 14:15
According to `git log`, `doc/Cryptol.pdf` was added in commit 2cb904ec468a3d627b300b7a7e6fd1bcf160d223 on May 15 this year. The log message for commit 5100132e4c4ecb35ea8deddca529b0e97ec9ced7, dated July 28, includes the item "Remove duplicate copy of Programming Cryptol", and removes the `doc/Cryptol.pdf` file. So it looks like the problem is already fixed.

Way back in the git history, I also found 72cd17c11bf851f1adda7c96c252c5b49961bc02, dated Apr 23, 2014, entitled "change name of book pdf". This is when the name of the cryptol book in the makefile was changed from `Cryptol.pdf` to `ProgrammingCryptol.pdf`. (`Cryptol.pdf` is still the name of the original file generated by latex in a temp directory before it is copied into `docs` by the makefile.) Perhaps this explains why a duplicate `Cryptol.pdf` might have been accidentally committed in the first place.

**Comment by brianhuffman** [comment] 2020-11-17 14:17
Actually I'm not 100% sure if the actual problem is fixed; the duplicate pdf is no longer checked in, but we need to check whatever script we use to generate the release tarballs to make sure that the tarballs don't contain duplicate pdfs.

**Comment by atomb** [comment] 2020-11-17 16:43
Yeah, it looks like the nightly build from last night still includes both. I see how to fix it, though. There's an unnecessary copy  in one of the Makefiles.

**Closed** 2020-11-17 17:26 UTC
Labels: bug, docs, low-hanging fruit, maybe-fixed
