### ISSUE TITLE
Tests are brittle w.r.t. solver versions

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol#584] opened 2019-03-19 18:13 UTC
The current test suite for Cryptol includes a few expected output files that include the satisfying assignments discovered by the solver (generally Z3). For a given version of a solver, these seem to be consistent, but I've been seeing spurious test failures on builders that have different solver versions installed. We could make one version of Z3 the canonical one to use during testing. I'd prefer an approach that was less brittle, but I'm not sure exactly what that would be at the moment.

**Comment by brianhuffman** [comment] 2019-03-20 01:23
Here are some possibilities, from easiest to hardest to implement:

1. Specify the exact version of Z3 and other solvers to use for the test suite.
2. Add a `:set` option to Cryptol to suppress printing of counterexamples, and just print e.g. "SAT".
3. Add support for non-exact text matching to the cryptol test runner. For example, we might allow the expected-output files to contain wildcards or regexes within the text.

Option 3 would be would be useful not only for robustness w.r.t. solver versions, but also for type checker error messages with generated unification variables like ``?fv`862``. These generated names are affected whenever any declarations are added or removed from the cryptol prelude.

**Comment by yav** [comment] 2019-03-20 04:01
I thought the issue was that sometimes we just find a whole different solution, e.g. for  N queens, so it'd be hard to specify what to expect.

As for the type variables, I hope it would be much less of an issue once I get a chance to implement the variable normalization algorithm we've discussed.

My vote would be for something like 2, and we also change the tests to validate the found example using the `it` variable.

**Comment by LeventErkok** [comment] 2019-03-21 23:54
@yav @atomb @brianhuffman This is a constant trouble with SBV as well; but there I insist on testing against the latest z3 build out of their nightly to keep things fresh. It's a headache especially for doctests; but it's the price to pay since z3 is a moving target itself. I thought about some regex-based checks myself, but there's just too much variation and it's probably not worth the investment.

Iavor: Regarding validation for SAT: That's precisely what the `:set prover-validate = on` setting does for you, I think Aaron already merged that in. So you don't even have to lift a finger to have that for free. (Of course, you can re-validate at the Cryptol level as an extra check, but validation by SBV should catch most issues.)

**Comment by yav** [comment] 2019-03-25 23:22
OK, I've added an option `show-examples` (True by default) that control if we print (counter)examples.  I also modified `regression/r03` to not print the examples, so hopefully the test suite should be a bit more reliable.

**Comment by atomb** [comment] 2019-10-25 18:44
I think the `show-examples` option may be enough to solve this problem for now. There are still some issues regarding tests on Windows, where paths are written differently, but that's a separate issue.

**Comment by robdockins** [comment] 2020-06-05 17:28
Anything else to do here?

**Comment by robdockins** [comment] 2020-11-19 01:21
I'm going to claim this is done.  As long as we make sure to set the `show-examples` to `no` in the test suite, we shouldn't be too tied to solver versions.

**Closed by robdockins** 2020-11-19 01:21 UTC
Labels: maybe-fixed, test-framework

**Comment by LeventErkok** [comment] 2020-11-19 01:30
@robdockins 

Perhaps you're already doing this; but if you're leaving out examples from gold files, a good route is to actually use SBV's `validateModel` feature, which at least makes sure the model returned from the solver satisfies all the constraints. There are a few things `validateModel` cannot handle (like FP operations with rounding modes other than round-nearest-ties-to-even, amd uninterpreted functions), but I believe (almost?) all of Cryptol should remain in the subset that can be fully validated.

See here for details: https://hackage.haskell.org/package/sbv-8.9/docs/Data-SBV.html#v:validateModel
