### ISSUE TITLE
Use of `random <lit>` in `:sat` or `:prove` should be concretely evaluated 

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#279] opened 2015-10-09 00:10 UTC
Notice:

```
> :sat \x -> x == (random 0 : [128])
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< ---------------------------------------------------
  Revision:  c07f97a9945231e4a4d7298bc64e8b7267c650d7
  Branch:    master (non-committed files present during build)
  Location:  Cryptol.Symbolic.Prims.evalECon
  Message:   can't symbolically evaluae ECRandom
%< ---------------------------------------------------
```

**Comment by LeventErkok** [comment] 2015-10-13 18:27
Duplicate of: https://github.com/GaloisInc/cryptol/issues/201

**Closed** 2015-10-13 22:48 UTC
Labels: duplicate
