### ISSUE TITLE
Parse error with nested tuple projections

### ISSUE THREAD

**Issue by ulidtko** [GaloisInc/cryptol#892] opened 2020-09-14 09:08 UTC
Hi!

Section 1.7 of [Programming with Cryptol](https://github.com/GaloisInc/cryptol/master/docs/ProgrammingCryptol.pdf) says *"Nested projections are also supported."* and proceeds to give an exercise which fails on **version 2.9.1**:

```
Cryptol> ((1, 2), False, (3-1, (4, True))).2.1

Parse error at <interactive>:1:35,
  unexpected: 2.1
```

I acknowledge that pattern-matching is a nicer way to do it anyway; but for a textbook exercise, it'd be cool to stay not broken.

**Comment by brianhuffman** [comment] 2020-09-14 16:25
Duplicate of #876.

**Closed by brianhuffman** 2020-09-14 16:25 UTC
