### ISSUE TITLE
Operator === is not mentioned in ProgrammingCryptol.pdf

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#244] opened 2015-06-19 18:44 UTC
The operator `===` is not discussed in the documentation. Equality between functions is discussed in section 2.16:

> Note that equality is defined on function types (i.e., `a b (Cmp b) => (a -> b)
> -> (a -> b) -> a -> Bit`).

But no mention is made of the `===` operator.

**Comment by dylanmc** [comment] 2016-03-09 15:30
Happy to add it, some good pedagogical examples would be appreciated.

**Comment by jpziegler** [comment] 2016-03-10 16:35
One reason to use it is to make equivalence proofs look more concise:
```
type multiplier = ([8], [8]) -> [8]

multiply : multiplier
multiply(a, b) = a * b

multiply_by_addition : multiplier
multiply_by_addition(a, b) = xs@b
  where xs = [0] # [ x + a | x <- xs ]

theorem = multiply === multiply_by_addition
long_theorem a b = multiply(a,b) == multiply_by_addition(a,b)
```
Unfortunately, using `===` in this context has the drawback that using the `property` keyword in front of `theorem` results in a type error. (It works just fine with `long_theorem`.)
```
property theorem = multiply === multiply_by_addition
```
```
Loading module Cryptol
Loading module Main

[error] at :1:1--11:62:
  The inferred type for theorem is ambiguous.
[error] at ./triple_equals.cry:10:20--10:53:
  Type mismatch:
    Expected type: Bit
    Inferred type: ?i9 -> Bit
  where
  ?i9 is 1st type parameter
         of expression (===)
         at ./triple_equals.cry:10:20--10:53
```
To make it work, the property gets uglier, since you need to do something like:
```
property theorem x = (multiply === multiply_by_addition) x
```
That's kind of unfortunate, since the initial argument was that `===` makes proofs prettier. But if it doesn't work well as a `property`, then what's the point?

Another drawback of `===` is that it requires the functions being compared to have exactly one parameter, so functions need to be written in "tuple-style" rather than "Curried-style".

Any way to address these drawbacks?

Any other examples of where `===` is useful?

**Comment by brianhuffman** [comment] 2016-03-10 16:44
For the use of `===` with `property`, see also #312 (which was closed as a duplicate of #224).

**Comment by dylanmc** [comment] 2016-04-28 15:56
Let's leave this out of the documentation until #224 is fixed.

**Comment by atomb** [comment] 2018-07-23 20:20
Commit 35452a6a adds an example of using `===`. Should we add anything more?

**Closed** 2018-07-26 20:49 UTC
Labels: docs
