### ISSUE TITLE
lg2 type operator doesn't work 

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#248] opened 2015-06-22 17:53 UTC
Here's a minimal example:

    module test where
    foo : [lg2 16]
    foo = zero

    [error] at ./test.cry:2:8--2:14
        Expected a type named 'lg2' but found a value instead

The same program works if I change `lg2` to `width`.

**Comment by yav** [comment] 2015-06-22 17:57
`lg2` and `width` overlap a lot.  There was a discussion on the Cryptol list some time ago to simply remove `lg2`, and so I removed it last week.   So, this is expected behavior, and we should use `width` instead.

**Comment by brianhuffman** [comment] 2015-06-22 18:01
Here's the actual array-update function (from one of our saw-script examples) that broke:

    update : {n, a, i} (fin n, fin i, i >= lg2 n) => [n]a -> [i] -> a -> [n]a
    update xs i y = [ if i == j then y else x | x <- xs | j <- [0...] ]

How would you express an equivalent type signature using `width`?

**Comment by yav** [comment] 2015-06-22 18:19
Is there anything wrong with:

    update : {n, a, i} (fin n, fin i, i >= width n) => [n]a -> [i] -> a -> [n]a
    update xs i y = [ if i == j then y else x | x <- xs | j <- [0...] ]

Although I might be missing something as the constraint on the index seems backwards?

**Comment by brianhuffman** [comment] 2015-06-22 18:28
The constraint is not backwards. The constraint is there to make sure that at most one position gets updated, or equivalently, the used part of `[0...]` does not wrap around.

Simply replacing `lg2` with `width` makes the type too specific: With `lg2` we can use a 4-bit index with a 16-element array, but with `width`, the constraint would require a 5-bit index.

I think I can express the constraint equivalently as `2^^i >= n` for now. Alternatively, the original type signature works if I define `lg2` myself as `type lg2 n = width (max n 1 - 1)` which I believe is equivalent to what the original `lg2` meant.

**Comment by brianhuffman** [comment] 2015-06-22 18:32
@yav: Can you point me to the Cryptol list discussion you mentioned? I can't seem to find it in the cryptol-users archives.

**Comment by yav** [comment] 2015-06-22 18:38
It was on cryptol-team list, I am not sure where that gets archived.  There was not a lot of discussion as usual:  however, Dylan did say that he found some places where he'd used `lg2` but meant to use `width`.

It's easy enough to add it back if you guys are using it, but I'd really prefer to cut down on the functions, especially when there is so much overlap between the two.  I must say I kind of like the exponential version.

**Comment by krisztianpinter** [comment] 2015-06-22 18:52
what is an easy way to calculate lg2 without lg2? suppose you have 4:[8].

what is an easy way to check if a number is power of two? it was (2^^(lg2 a) == a), now what? again, a might start with a bunch of zeros.

**Comment by weaversa** [comment] 2015-06-22 21:04
Woh. `lg2` and `width` are both useful in their own right! I strongly suggest discussions about removing operators be moved to a public forum.

**Comment by brianhuffman** [comment] 2015-06-22 21:07
Keep in mind that this discussion is only about the `lg2` *type operator*. The function `lg2 : {a} (Arith a) => a -> a` is still there.

**Comment by weaversa** [comment] 2015-06-22 21:07
I know.

**Comment by brianhuffman** [comment] 2015-06-22 21:08
I suggested to @yav that we could add the declaration `type lg2 n = width (max n 1 - 1)` to the Cryptol prelude; how would that work for everyone?

**Comment by krisztianpinter** [comment] 2015-06-22 21:14
i see now. with types, width seems OK.

**Comment by weaversa** [comment] 2015-06-22 21:14
I can't get your suggestion to parse. what is `max n 1 - 1`?

**Comment by weaversa** [comment] 2015-06-22 21:19
Interestingly, `cryptol` has a horrible time with the following:
```
Cryptol> `(width(max 10 1 - 1)) : [29]
```
Increasing `29` to anything larger seems to cause exponential delays. Hence, this may not be a good replacement.

**Comment by brianhuffman** [comment] 2015-06-22 21:33
I would consider this to be a completely separate performance bug, especially considering that

    `(width 9) : [29]

is evaluated instantly. I'm going to do a bit of profiling now...

**Comment by yav** [comment] 2015-06-22 22:01
This was because the evaluation rule for `max` got lost somehow.  It should be fixed now.

**Comment by weaversa** [comment] 2015-08-17 17:48
I would like to see `type lg2 n = width (max n 1 - 1)` added to the prelude.

**Closed** 2016-05-05 00:54 UTC
Labels: low-hanging fruit, priority
