### ISSUE TITLE
Constraint solver and defaulting.

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#116] opened 2014-10-01 20:58 UTC
See example under issuse/issue218

    t = (0x1, { key = 4, value = "goodbye"})
    bug218Fixed = (t.2.value == t.2.value)

**Comment by dylanmc** [comment] 2016-03-08 18:12
This seems the same as #2

**Comment by robdockins** [comment] 2016-05-06 20:06
Duplicate of #2

**Closed by robdockins** 2016-05-06 20:06 UTC
Labels: typechecker
