### ISSUE TITLE
laziness of conditionals

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#419] opened 2017-05-13 19:35 UTC
The reference evaluator and REPL evaluator disagree again:

    Cryptol> if error "boo" then () else ()
    
    Run-time error: boo
    Cryptol> :eval if error "boo" then () else ()
    ()

Similarly with infinite recursion:

    Cryptol> if b then () else () where b = b
    
    <<loop>> while evaluating (at <interactive>:1:28--1:29, <interactive>::b)
    Cryptol> :eval if b then () else () where b = b
    ()

**Comment by robdockins** [comment] 2017-05-19 18:53
This seems like essentially the same problem as #442.  Basically, we should only demand the value of the conditional test if the caller is going to demand at least one bit of the output... and there are no bits of output at the unit type.

**Comment by brianhuffman** [comment] 2019-10-25 23:27
Duplicate of #422.

**Closed by brianhuffman** 2019-10-25 23:27 UTC
Labels: semantics
