### ISSUE TITLE
`width` and more vacuous constraints

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#212] opened 2015-05-07 16:32 UTC
@yav Much like issue #208 in which there were vacuous constraints (now fixed, I can not reproduce in 2.2.3 or HEAD it seems), there are vacuous width constraints required in 2.2.3 and HEAD.  The code is included in commit 94abebdf01718eae61b27c479edccf346de8bee3.

For example, it would be nice to have the rules:

```
width x == const ==> width x >= const
const >= width (x+1) ==> const > width x
const >= width n     ==> fin n
```

**Comment by TomMD** [comment] 2015-05-07 16:58
I'll also not that at least version 2.2.3 does not know `width a b == width b a`, I've had to add otherwise-identical constraints for each.

**Comment by acfoltzer** [comment] 2015-05-07 17:28
Since 2.2.3 does not use the new constraint solver, I would recommend only using HEAD to test such issues unless you notice a regression from 2.2.3 to HEAD.

**Comment by TomMD** [comment] 2016-01-05 23:56
All execpt the last issue in the example file has been fixed.  I currently see:

```
[error] at ./issue212.cry:24:1--26:28:
  Failed to validate user-specified signature.
    In the definition of 'Main::take_knows_no_bounds', at ./issue212.cry:24:1--24:21:
      for any type n
        fin n
        n >= 4
      =>
      n == 4 + (?p18 - n % 4)
        arising from
        matching types
        at ./issue212.cry:26:26--26:28
  where
  ?p18 is 2nd type parameter
          of expression Cryptol::take
          at ./issue212.cry:26:8--26:12
```

**Comment by acfoltzer** [comment] 2016-01-12 23:25
Interestingly, you can specify just the `back` type argument and get it to typecheck:

```
take_knows_no_bounds : {n} (fin n, n >= 4) => [n][8] -> [4 - (n%4)][8]
take_knows_no_bounds ns = foo
 where
 foo = take `{back = n - (4 - (n%4))} ns
```

@TomMD: because there's a workaround, are you alright with releasing 2.3.0 without a fix for this? Let's still keep this ticket open, though, because the original program ought to work.

**Comment by TomMD** [comment] 2016-01-13 00:55
@acfoltzer I am ok with that.  I'm going through the laundry now - ChaCha20 still took a change to get the typechecker to play nice but I'm OK with how it turned out (@dylanmc  might care, fc04e415d74a59d1db99fc93e7d82c4430751eab).

**Comment by robdockins** [comment] 2017-10-02 22:19
This bug is very close to fixed now.  The only remaining issue is that the following sill wants a `fin n` constraint.

```
can_not_width : {n} (64 >= width (8*(n+1))) => [64]
can_not_width = zero # (`n : [width n])
```

It seems that the interaction with `#` is important, because the following checks with no problem:
```
asdf : {n} (64 >= width (8*(n+1))) => [64]
asdf = `n
```

**Comment by yav** [comment] 2017-10-03 18:02
In the example of @robdockins I get the following error:
```
      for any type n
        64 >= width (8 * (1 + n))
      =>
      64 == ?y13 + width n
        arising from
        matching types
        at ./t.cry:2:17--2:40
      fin ?y13
        arising from
        use of expression (#)
        at ./t.cry:2:17--2:40
  where
  ?y13 is 1st type parameter
          of expression (#)
          at ./t.cry:2:17--2:40
```

This means that, basically, Cryptol can't figure out how wide of `zero` we need (i.e., type `?y13`).  We probably want it to write `64 == ?y13 + width n` into `(?y13 = 64 - width n, 64 >= width n)` because this would define the unification variable.  From there onwards, Cryptol ought to be able to simply the remaining constraints.

**Closed** 2017-10-03 20:17 UTC
Labels: typechecker
