### ISSUE TITLE
random doesn't work with :sat and :prove

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#201] opened 2015-04-16 00:15 UTC
This is a stupid thing to want to do, but I was experimenting with different solvers and just wanted a random problem instance.  So I tried :sat with an expression containing `random`.  Big mistake, apparently:

```
Cryptol> :sat \x -> (x:[8]) == random 123
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  300ed3cba993e49d0dbe34205d4f404524a3ffdd
  Branch:    HEAD (non-committed files present during build)
  Location:  Cryptol.Symbolic.Prims.evalECon
  Message:   can't symbolically evaluae ECRandom
%< --------------------------------------------------- 
```

The interpreter exits after printing this.

**Comment by acfoltzer** [comment] 2015-04-16 00:52
Thanks for the report; this should be an exception (like when indexing off the end of a sequence) rather than a panic.

**Comment by acfoltzer** [comment] 2015-04-16 00:56
@brianhuffman, could you do a pass to see which `panic`s are there for situations which should never arise because of some precondition enforced by the typechecker vs. those like this that could come up just for bad inputs?

**Comment by LeventErkok** [comment] 2015-05-05 02:40
@acfoltzer I don't see why this should be an exception.

Surely, `random 123` is a well-defined deterministic value; and thus this query should execute just fine. No?

**Comment by brianhuffman** [comment] 2016-03-08 19:53
We should definitely make it report a nice error message instead of crashing. Beyond that, we need to think about what we want: Should we evaluate function `random` on concrete arguments only? Should we print a warning message when we do?

**Comment by robdockins** [comment] 2017-07-27 22:29
Duplicate of #364

**Closed by robdockins** 2017-07-27 22:29 UTC
Labels: bug, low-hanging fruit
