### ISSUE TITLE
Exercise 4.6 produces an error

### ISSUE THREAD

**Issue by bboston7** [GaloisInc/cryptol#757] opened 2020-06-09 18:19 UTC
Exercise 4.6 in the cryptol book gives the example:

```
property widthPoly x = (w == 15) || (w == 531) 
  where w = width x
```

However, putting this in a file and loading it with cryptol results in the error:

```
[error] at ./c4.cry:10:13--10:18
    Expected a value named 'width' but found a type instead
    Did you mean `(width)?
```

**Comment by brianhuffman** [comment] 2020-06-09 18:54
The value-level function `width` was renamed to the less-misleading name `length` multiple releases ago. This particular example will be trivial to fix, but we really ought to have all the example code from the book included as part of our test suite.

**Comment by bboston7** [comment] 2020-06-19 19:42
It appears that this example was actually fixed a while ago, but that the PDF on the website is just out of date with respect to this repo.  I'm unassigned myself but leaving this open because I'm not sure how to resolve the second part of your comment (that the example code be run as part of a test suite)

**Comment by robdockins** [comment] 2020-07-29 00:02
It seems like the fundamental problem here was an out-of-date PDF right?  I think we can close the other aspect of this as duplicate of #613.

**Comment by atomb** [comment] 2020-07-29 00:08
Yeah, I'm leaving it open until I upload the new PDF, but it's otherwise fixed.

**Comment by atomb** [comment] 2020-07-29 16:53
And now the PDF is updated.

**Closed by atomb** 2020-07-29 16:53 UTC
Labels: docs
