### ISSUE TITLE
Command :safe

### ISSUE THREAD

**Issue by Johanvdberg** [GaloisInc/cryptol#472] opened 2017-10-11 00:37 UTC
I the article " Pragmatic equivalence and safety checking in Cryptol" where is an example using the command :safe. 

With Cryptol 2.5 the command is not recognized. Will the command be supported in the future again?

**Comment by atomb** [comment] 2017-10-16 15:42
We are hoping to support it in the not-too-distant future. Most of the pieces we would need are in place now, and it's mostly a matter of tying them together.

**Comment by brianhuffman** [comment] 2017-10-16 20:51
Duplicate of #284.

**Closed by brianhuffman** 2017-10-16 20:51 UTC
