### ISSUE TITLE
sha-1 spec on web-page off-by-one

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/cryptol#159] opened 2015-01-16 00:45 UTC
The SHA-1 spec on "Home" tag of cryptol.net says: (In the SHA-1 specification section)

 ... Each function f_t, where 0 <= t < 79, ...

And then goes on to define f, even when t = 79.

Funnily, the linked document does not have this issue, and it clearly says 0 <= t <= 79. And looks like you guys cut/paste'd this box from that document, but perhaps from an earlier version with that typo?

Would be good to fix that! Doesn't look good to have an off-by-1 in there on the very first page..

**Comment by dylanmc** [comment] 2015-01-16 02:25
It turns out that inconsistency is in the SHA-1 spec (!).  I sent an email to the folks at NIST, and they confirmed it, and will fix it in the next revision of that document. Oddly, I tried it both ways, and all the test vectors pass each way. I don't think I tried a :prove that they're the same thing...but that might be interesting!

**Comment by LeventErkok** [comment] 2015-01-16 05:14
Actually, the very link you provided on that page has the correct description (<= 79); I'm not sure which version of the document you're talking about @dylanmc.

In any case, if the tests pass in all cases, then that's an indication that the test-vectors you have are just not sufficient!

For :prove; it all depends on how Cryptol translates "error" these days; in the past, a ":safe" check would've caught the difference between the two versions, but I do believe ":safe" isn't implemented in Cryptol-2 yet.

**Comment by dylanmc** [comment] 2015-01-16 05:33
Wow - they seem to have edited the version of the document, but left the date 2012. I have a version of that same document on my hard-drive with the error. Huh!  Anyway, we do need to update the FIPS document-snippet. The Cryptol code is correct. I'll close this ticket once that fix has been made.

**Comment by weaversa** [comment] 2015-03-13 12:06
As Frank would say: https://www.youtube.com/watch?v=oPwrodxghrw

**Comment by dylanmc** [comment] 2015-04-09 16:24
website updated to reflect NIST's correction of the off-by-one.

**Closed by dylanmc** 2015-04-09 16:24 UTC
