### ISSUE TITLE
FoxChickenCorn (nee WolfGoatCabbage) Fails Typecheck

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#175] opened 2015-03-04 16:48 UTC
The FoxChickenCorn example currently fails to typecheck. I get the following error:

```
[error] at ./FoxChickenCorn.cry:30:1--32:55:
  Failed to validate user-specified signature.
    In the definition of 'FoxChickenCorn::validMoveSequence', at ./FoxChickenCorn.cry:30:1--30:18:
      for any type n
        fin n
        n >= 1
      =>
      fin (min n (n - 1))
        arising from
        use of expression FoxChickenCorn::all
        at ./FoxChickenCorn.cry:30:28--30:31

```

**Comment by jpziegler** [comment] 2015-03-04 18:58
marble.cry also fails when typechecking its `validMoveSequence` function.

**Comment by dylanmc** [comment] 2015-03-04 19:46
I am git bisecting as we speak. After we pin this down and fix it, we'll add funstuff to the regressions test suite.

**Comment by elliottt** [comment] 2015-03-04 22:58
It looks like this issue showed up originally in commit 28fdd44, which fixed a bug related to the handling of `fin` constraints.  The reworked constraint solver will be able to deal with this signature once it's merged in.

**Comment by weaversa** [comment] 2015-03-09 16:15
Can we have an eta for the reworked solver?

**Comment by atomb** [comment] 2015-03-16 22:59
The solver is feature complete now, but somewhat slower than the original. The current plan is to release Cryptol 2.2 in the near future, and then merge in the new solver so we can start tuning its performance so that it'll be on par with the current solver in time for the 2.3 release.

**Comment by weaversa** [comment] 2015-03-17 13:45
> The solver is feature complete now, but somewhat slower than the original.

Is your solver so slow 'cause it offloads to Явор? --- Speed it up now by getting more Явор!

**Comment by atomb** [comment] 2015-03-17 13:56
If you have any leads on where to get more Явор, we'll pay top dollar!

**Comment by brianhuffman** [comment] 2016-02-12 22:29
I just tried it out, and FoxChickenCorn.cry seems to work fine.

**Closed by brianhuffman** 2016-02-12 22:29 UTC
